### ISSUE TITLE
😬 (grimace) emoji missing?

### ISSUE THREAD

**Issue by ghost** [johannhof/emoji-helper#103]
I tried searching every term that [Emojipedia](https://emojipedia.org/grimacing-face/) uses, including copy/pasting the emoji (😬) directly and don't believe the "grimace" emoji is in the add-on! I wonder if others are missing?

Hope this can be addressed, but otherwise: fantastic plug-in. Saves a lot of time using emoji.

**Edit:** I should add that this is not a new emoji but part of the first release of emoji, Emoji 1.0 ([source](https://emojipedia.org/grimacing-face/)).

**Comment by kitroed** [comment]
This should be closed, "grimace" != "grimacing"

:grimacing:

**Comment by johannhof** [comment]
ok!
