### ISSUE TITLE
Someone forked this

### ISSUE THREAD

**Issue by rugk** [johannhof/emoji-helper#124]
Appearently someone who goes by the name "Emoji Library" forked this and created a new add-on:
https://addons.mozilla.org/de/firefox/addon/emoji-library/

I have not tried it yet, so I don't know for sure whether it is the same or what they changed.

**Comment by rugk** [comment]
So a [diff shows](https://try.diffoscope.org/ypkuxsyurcyq.html) they did not change much. Basically, they removed all credits and republished it. They added some empty background scripts and many more (unused, as it seems) permissions, (especially sensitive ones such as `<all_urls>`), so I do not really feel really well.

In any case, they certainly violated [the LICENSE](https://github.com/johannhof/emoji-helper/blob/master/LICENSE) by not including it/stating the original author.

**Comment by Prometheos2** [comment]
That may interest @johannhof...

**Comment by rugk** [comment]
I've already reported it via AMO's button there, but maybe we need more reports. 

So anyone reading this:
* Please report that fraudulent add-on.
* Possibly also add a vote and add a note/backlink here so users know this is an unauthorized fork.

**Comment by Azarilh** [comment]
The requests that addon is askin' for... "Access your data for all web sites".
So it's not just copied but also unsecure.

**Comment by LeoniePhiline** [comment]
The fork seems gone. @rugk I think you can probably close this.
