### ISSUE TITLE
Enable Keyboard Shortcut in Firefox

### ISSUE THREAD

**Issue by johannhof** [johannhof/emoji-helper#25]
Quoting @JimPinho at #20
> Is there a way [in Firefox] to open emoji sheet without having to click the toolbar icon (Ctrl + E, for instance)?

**Comment by BobbyWibowo** [comment]
Does it have to be Ctrl+E? On my case (Firefox 35), that hotkey will set focus to the search bar.

**Comment by johannhof** [comment]
Mmh I suppose I could put that in our new settings screen as well. :smile:

To keep it simple, I'd like to give a list of possible options. Any specific hotkey you'd like to have?

**Comment by BobbyWibowo** [comment]
~~Ctrl+Q and Ctrl+M could work. I prefer Ctrl+Q though.~~ I forgot Ctrl+Q is the standard for closing app.

**Comment by mikhoul** [comment]
Not a Shortcut but having the choice to have Unicode emojis or "standard" copied by default in the buffer would be GREAT !!!!  👯
