### ISSUE TITLE
Option for default copying :bbcode_descriptor: or unicode to clipboard

### ISSUE THREAD

**Issue by joen93** [johannhof/emoji-helper#26]
Perhaps you could add a "clipboard option", where the user can select whether the :bbcode_descriptor: or the unicode is copied to the clipboard by default, when clicking on an emoji 😄 

This would avoid extra clicks (especially for unicode users), because now the :bbcode_descriptor: is copied by default once the user clicks an emoji.

Just a minor improvement which (heavy) unicode users will love for sure 😉

**Comment by BobbyWibowo** [comment]
Came here from the Firefox Add-ons page.
So yeah, I'd love to have this option. Since I'm using this add-on on social networks to begin with.

**Comment by kudataz** [comment]
yes agree.. update it for code copied automatic or use flash copied ^^
