### ISSUE TITLE
Add option for window persistence

### ISSUE THREAD

**Issue by SpencerDub** [johannhof/emoji-helper#28]
Currently, the emoji helper window closes automatically when it loses focus. This means that if you want to copy more than one emoji in a row, you have to open the helper, select the first emoji, paste it, then open the helper *again*, find the next emoji, and so on.

Adding the option to keep the window open when it loses focus would improve this extension's functionality considerably.

(If this is already an option somewhere, then pardon the duplicate; I didn't see it.)

**Comment by johannhof** [comment]
Thanks for the suggestion :+1:
I think keeping the window open will be hard to implement using the normal SDKs.

I'd like to add a button to insert an emoji directly into the focused input field in your browser window without closing the extension. This is probably what you want to achieve  :grin: 

I'll pick up development on the [1.0 branch](https://github.com/johannhof/emoji-helper/tree/v1.0) soon. If you or anyone else know some JS I'd be happy to help you get going to implement the feature yourself.

**Comment by SpencerDub** [comment]
>I'd like to add a button to insert an emoji directly into the focused input field in your browser window without closing the extension. This is probably what you want to achieve :grin:

That would indeed do the trick! I'm an absolute novice at JS, so I don't think I'm the one to take the torch here, but I appreciate your quick feedback and look forward to seeing this feature!

Thanks a bunch!

**Comment by BobbyWibowo** [comment]
> I'd like to add a button to insert an emoji directly into the focused input field in your browser window without closing the extension. This is probably what you want to achieve :grin:
Yes! I was about to create a ticket to suggest this. Also, it'll be even better to have the ability to move the window position. And if possible, save the position so that it'll appear on the latest position.

**Comment by johannhof** [comment]
From the next release on the window will just appear below the button, like in Chrome. That's the correct behavior for popup windows, in my opinion. Firefox just didn't offer "button-binding" when I started developing.

**Comment by BobbyWibowo** [comment]
> From the next release on the window will just appear below the button, like in Chrome. That's the correct behavior for popup windows, in my opinion. Firefox just didn't offer "button-binding" when I started developing.

That will be even better! I actually wanted to suggest that, but considering that I just moved to Firefox recently, I thought there might be certain things that couldn't be done on it (including complex pop-up window from the add-on button).

**Comment by johannhof** [comment]
Closed by 36b8df1bc2fd77a5a6a25061336e8cad18efee43
