### ISSUE TITLE
Show emoji name when hovering the emojis

### ISSUE THREAD

**Issue by BobbyWibowo** [johannhof/emoji-helper#30]
Basically what I put on the title. If you're going to implement the feature to add emoji straight to focused input bar, it'll be best to be able to see the emoji's name when hovering it on the list. At the moment, since I tend to forget the actual meaning of certain emojis, I simply click on it to see its name from its BBCode descriptor.

**Comment by caske33** [comment]
Is this fixed now? Because when I hover over the emoji's it doesn't display a name. I'd love to have this functionality!

**Comment by johannhof** [comment]
@caske33 yes, sorry, I had some issues with deployment so it's not live yet. I'll take another look right now.
