### ISSUE TITLE
Small Bug in Firefox with the Icon.

### ISSUE THREAD

**Issue by mikhoul** [johannhof/emoji-helper#33]

**Comment by mikhoul** [comment]
The Icon is to big on the toolbar...   Icon is kind of stretched veritcally.

The Icon is 22 pixels High and should be max 20 pixels  (standard is 20X20 Pixels for the toolbar)

http://i.imgur.com/DoFChZk.png
![zzz_2015-03-22_23-23-42](https://cloud.githubusercontent.com/assets/5678673/6773673/df782ee6-d0ea-11e4-9103-52ed599097d2.png)

**Comment by johannhof** [comment]
:hushed:

I'll try to fix.

**Comment by johannhof** [comment]
Mmh was that fixed back in the day? I'll close this, feel free to comment if this is not fixed.
