### ISSUE TITLE
Not compatible with Pale Moon 25.3.x

### ISSUE THREAD

**Issue by KNTRO** [johannhof/emoji-helper#37]
Hi Johann,

Please, add support for Pale Moon 25.3.x, as Emoji Cheatsheet 1.0.0 isn't compatible with this web browser.

Thank you a lot.

**Comment by johannhof** [comment]
Hey there,

I'll try to look into it if I find the time, don't get your hopes too high on that :confused:

If you want to rollback to an older version they're all available on the [releases page](https://github.com/johannhof/emoji-helper/releases)

Cheers

**Comment by johannhof** [comment]
Oh, and if you have any means to find out what is causing the incompatibility I'd love to hear more about it :+1:

**Comment by KNTRO** [comment]
Got it! I'll let you know if I get some help with this! ;)

**Comment by KNTRO** [comment]
Hi again Johann,

I got a replied from Matt A Tobin, one of the brains behind Pale Moon and [he explained here] (http://upvot.es/1FIkhvK) why the Emoji Cheatsheet add-on doesn't work with Pale Moon.

Hope this technical info helps you to make your add-on compatible with this wonderful web browser.

Thanks a lot!

**Comment by johannhof** [comment]
Hey, 

thanks for researching this! As I feared, Pale Moon does not support the toggle button feature that we use to display the extension button. This can be worked around using the [Widget API](http://dev.addons.palemoon.org/jetpack/modules/sdk/widget.html). 

I'll leave it in the backlog until I find the time or someone else comes around to do it.

**Comment by KNTRO** [comment]
Thanks a lot!
