### ISSUE TITLE
Slow load time

### ISSUE THREAD

**Issue by Blendertom** [johannhof/emoji-helper#44]
Sometime is can take upwards of 20 seconds for the drop down to appear after clicking it in Chrome. It works fine on Firefox.

**Comment by johannhof** [comment]
That's due to the way the Chrome extension system works, hard to fix, the images are pretty small already. Sorry :pensive:

**Comment by Blendertom** [comment]
No worries, it's still the best way to add emoji from chrome. Thanks for the
reply.

Stay awesome
Yousuf



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.55&pv=5.0.2&source=email_footer_2&ln=en] On Wed, Nov 11, 2015 at 2:52 am, Johann Hofmann < notifications@github.com [notifications@github.com] > wrote:
That's due to the way the Chrome extension system works, hard to fix, the images
are pretty small already. Sorry:pensive: [https://assets-cdn.github.com/images/icons/emoji/unicode/1f614.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/johannhof/emoji-helper/issues/44#issuecomment-155578253] .[https://github.com/notifications/beacon/ADRzNXPfrRLP4SBNLZlMyILikyszu5mJks5pEl6ggaJpZM4FceT7.gif]

**Comment by x-a-n-a-x** [comment]
I noticed the same slow load time under Firefox (I currently use Firefox 46).

Emoji-helper is the slowest one to load, among the 10 addons that I have installed.
I would say it takes up to 5-7 seconds (after firefox is launched) for the icon to load on the firefox's toolbar. It's a bit surprising for a simple addon that only suggest emojis for copy-paste..
