### ISSUE TITLE
[Firefox] - Emoji Toolbar Image is way too large.

### ISSUE THREAD

**Issue by macleodsawyer** [johannhof/emoji-helper#48]
The latest firefox updates makes the thumbnail used in Firefox incredibly large.

![2015-09-03_06-57-55](https://cloud.githubusercontent.com/assets/4322153/9657712/1fa64904-5209-11e5-918e-ed539bc64fb2.png)

A simple resize of the image should work, please fix this. 

Other wise great extension! +1

**Comment by johannhof** [comment]
yeah it's weird, this seems to be happening to people randomly, it's okay for me. I'll try to resize, but would you mind reinstalling the add-on to be sure?

**Comment by macleodsawyer** [comment]
I've reinstalled it, still has that same issue + I used a different profile to test.

**Comment by macleodsawyer** [comment]
Figured out the issue, albeit stupid, but its an issue with a lot of Firefox complete themes. 

Resizing will probably fix it for anyone with a complete them on still.

**Comment by x-a-n-a-x** [comment]
I use the latest Firefox version and I don't have this big icon.

To know what is causing this behaviour, I would try to disable all add-ons except emoji-helper, then re-enable them all one by one (to know which one is making the icon bigger).

**Comment by johannhof** [comment]
So, knowing a bit more about Firefox add-ons now, this is unlikely to be solved by resizing any icon. It just appears sometimes, Firefox bug for now. I'll close this if no one minds.
