### ISSUE TITLE
Option to clear the History

### ISSUE THREAD

**Issue by x-a-n-a-x** [johannhof/emoji-helper#50]
It could be interesting to be able to empty the History in the settings :

![screenshot001](https://cloud.githubusercontent.com/assets/1732773/10286821/f973f0ce-6b8f-11e5-8ef0-91d415f0f2be.png)

**Comment by johannhof** [comment]
Thanks for the suggestion! I've got my hands pretty full atm, if someone wants to give this a try I'd be happy to give suggestions, shouldn't be hard to implement.
