### ISSUE TITLE
firefox refuse remember settings

### ISSUE THREAD

**Issue by boxcat1** [johannhof/emoji-helper#51]
As i get in settings and mark to use unicode in clipboard, after restarting firefox, this setting gets back to : joy : marking. Kinda annoying.
Firefox version 41.0.1 on Windows 7 64bit.

**Comment by johannhof** [comment]
Most Firefox problems are related to broken profiles, please [try creating a new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) and test if it works correctly. If that's the case, there's not much we can do here.

**Comment by boxcat1** [comment]
i don't know how, but problem vanished away itself. (its not like i forgot to restart firefox or anything, its just got fixed somehow).

**Comment by johannhof** [comment]
Yup, Firefox is unfortunately pretty often experiencing these phantom-UI problems :ghost:

Thanks for reporting though :white_check_mark:
