### ISSUE TITLE
Improvement on V 1.1.1

### ISSUE THREAD

**Issue by mikhoul** [johannhof/emoji-helper#52]
Hi Johann,

I was happy to see the option to insert directly emoji this morning....   

But it's not available for UNICODE sadly  :sob:

Could you add an option _**"Insert UNICODE to Active Input"**_ ?
It would be very useful. 

Have a good Week-End from Canada !

**Comment by johannhof** [comment]
Hey @mikhoul , @michyprima actually implemented that, unicode sounds like a useful addition.

**Comment by johannhof** [comment]
Oh, and I wish you a good weekend as well :palm_tree:

**Comment by johannhof** [comment]
I'll dupe this with #72
