### ISSUE TITLE
paw prints is missing the unicode symbol

### ISSUE THREAD

**Issue by KonomiKitten** [johannhof/emoji-helper#54]
When using "paw_prints" the Unicode symbol is missing but when using "feet" the alternative name for "paw_prints" the Unicode symbol is present. After using both of them I now have two of the same Emoji for paw prints because "paw_prints" and "feet" don't seem to be aliased as one single Emoji.

**Comment by johannhof** [comment]
Thanks, I added the unicode symbol. Aliasing could indeed be much better, but it's such a simple extension...

**Comment by KonomiKitten** [comment]
@johannhof thanks for the quick fix!
