### ISSUE TITLE
emoji-helper icon to big in FF ...

### ISSUE THREAD

**Issue by Dutchglory** [johannhof/emoji-helper#68]
emoji-helper icon is to big in FF 45.0b6
![screenshot_1](https://cloud.githubusercontent.com/assets/461485/13206748/0c142f36-d905-11e5-8cbd-59e6540bcb57.png)

can you change..??

**Comment by johannhof** [comment]
It's a WebExtension now, either the problem doesn't exist anymore or it's out of my control.
