### ISSUE TITLE
satisfied and laughing are the same smiley

### ISSUE THREAD

**Issue by rugk** [johannhof/emoji-helper#69]
`:satisfied:` :satisfied: and `:laughing:` :laughing:

But only "laughing" has an unicode character: 😆 (`😆`)

As satisfied is listed at the top in the panel it is annoying to not have an unicode character there for me as I've set the default action to "copy the unicode char".

**Comment by i-cant-git** [comment]
I can confirm ":satisfied:" emoji doesn't have Unicode character on right box (box is empty).

![satisfied](https://cloud.githubusercontent.com/assets/16619091/15880413/bd377348-2d35-11e6-84ff-f46274509492.png)

**Comment by johannhof** [comment]
v2.0 removed satisfied.
