### ISSUE TITLE
No extension for Safari in official store

### ISSUE THREAD

**Issue by Atcold** [johannhof/emoji-helper#70]
I cannot find this extension in Safari's official store... Am I missing something?
In Chrome it was just wonderful!

**Comment by Croydon** [comment]
Step 1) Read the readme: `Visit http://johannhof.github.io/emoji-helper for download links from the official stores.`
Step 2) Go to: http://johannhof.github.io/emoji-helper
Step 3) Click on `Download for Safari`
Step 4) https://extensions.apple.com/details/?id=com.johann-hofmann.emoji-VQE5S3G4ED

**Comment by Atcold** [comment]
I just clicked on the link of step 4)
![screenshot 2016-04-01 02 30 41](https://cloud.githubusercontent.com/assets/2119355/14199358/c9e93b9e-f7b1-11e5-98cb-b081fe8ecf1e.png)

**Comment by Croydon** [comment]
The site is showing me a "Download Safari 6" link. Maybe @johannhof didn't mark it as compatible with Safari 9?

**Comment by johannhof** [comment]
Unfortunately Apple now requires you to buy a subscription to their developer program to publish extensions, which I will not do on principle. See https://www.reddit.com/r/apple/comments/397bn6/apple_wants_me_to_pay_100_to_continue_publishing/

Sorry! :heart:

**Comment by Atcold** [comment]
Well... you don't need to publish it. Just post the extension, like [*Vimari*](https://github.com/guyht/vimari) does. Then we double click it :wink:
