### ISSUE TITLE
GitHub now supports more emoji. Let's add them!

### ISSUE THREAD

**Issue by elamperti** [johannhof/emoji-helper#85]
GitHub now supports a lot of new emoji! (proof: :croissant: :thinking: :bacon: )

It would be great if they could be added to the helper. Maybe the icons should be updated too, to match the ones used by GitHub.

Related issues:
  * #49 - Unicode 7.0 & 8.0 emoji missing 
  * #73 - Unicode update / Add Unicode 9 emoji

**Comment by emojimad** [comment]
Yes where is emoji one and newer ones now?? for chrome add on

**Comment by johannhof** [comment]
Added them! :artificial_satellite:

**Comment by elamperti** [comment]
@johannhof fantastic! Great work 😁 Thank you!
