### ISSUE TITLE
Support for Emoji 5.0 / 2017? + Thanks

### ISSUE THREAD

**Issue by mgonzales71** [johannhof/emoji-helper#89]
@johannhof 

I was curious first is this extension still under development?  If so will you be adding support for the newest emoji's?

http://blog.emojipedia.org/final-2017-emoji-list/

I have looked at many options for emoji browser extension support and you have done a great job at making the interface simplistic but easy to use without getting in the way or being way too much. 

Thanks,

Mario

**Comment by johannhof** [comment]
> I was curious first is this extension still under development? If so will you be adding support for the newest emoji's?

I've been struggling to maintain it recently, but I pushed another update that should resolve your request. Thank you.
