### ISSUE TITLE
Bug with WebExt Installation in Firefox

### ISSUE THREAD

**Issue by mikhoul** [johannhof/emoji-helper#93]
You forgot to include the an ID in the manifest of the addon so the addon  woun't install and is detected as corrupt.

Just add an ID in the manifest and everything will be fine: http://i.imgur.com/xZTKarh.png

Regards :octocat:

**Comment by johannhof** [comment]
Huh, installs fine for me. I thought they dropped that requirement. What version of Firefox are you on?

**Comment by mikhoul** [comment]
FF 54.0.1  Sure you are in Dev mode so it's why it install properly.  

The Mozilla documentation is very poor and misleading on this subject (ID) since last year I found at least 12 others addoons (webext) with the same problem (missing ID)  😉 .

Many of those addon had only 1-2 users for months since no casual user could try them 🤒 .

Regards  :octocat:

**Comment by johannhof** [comment]
But, I can install it even on a fresh profile in 54. I'll check with the Add-Ons team.

**Comment by mikhoul** [comment]
Do what you want but the solution is just to sign the addon. 

Mozilla as usual have their head in their b**ut to busy to make cosmetic changes, copying Chrome and removing useful features instead of fixing real bugs that are well know:  https://github.com/mozilla/addons-server/issues/3183

Good luck with them  :octocat:

**Comment by johannhof** [comment]
You know I work for Mozilla, right? :wink:

Ok, so I meant I can install it from AMO. Are you building your own version?

**Comment by MarkRH** [comment]
Yep, I can't install 2.0.1 using the internal update mechanism or directly from the AMO website. It thinks it is corrupt. Firefox 54.0.1.

**Comment by MarkRH** [comment]
Well, version 2.0.1 installed fine in version 55 so it must just not be compatible with versions below it.

**Comment by johannhof** [comment]
Huh, sorry about that. Not sure what to do here.

**Comment by johannhof** [comment]
Oh, maybe support for leaving out the manifest ID landed in 54? In any case since we're on 55 now I'll close this.
