### ISSUE TITLE
Control-E no longer functions

### ISSUE THREAD

**Issue by caturday3883** [johannhof/emoji-helper#94]
Hitting Control-E with the extension no longer opens the emoji menu. Checking the settings only lets me set up how the emojis are copied, not which command opens the emoji helper extension.

I am running Ubuntu 16.04, Firefox 54.0 (64 bit)

**Comment by johannhof** [comment]
Yes, sorry, didn't think of that in the WebExtension transition. Will fix.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands

**Comment by johannhof** [comment]
Ok so I had to change it to Ctrl+Shift+E, because Ctrl+E is a keyboard shortcut that is already used by Firefox, in a5ed90c7f6263f10d2002d0493311933f4cf64bc. I hope that works for you, sorry for the inconvenience.

**Comment by MarkRH** [comment]
Ctrl-Shift-E conflicts with the Network tab of Developer Tools which got changed with Firefox 55.

**Comment by iEFdev** [comment]
@johannhof, sorry to open this old one.

There's a difference int the behaviour now (as an Webextension), compared to before.

⌘⇧E
The shortcut works fine, as long as it sits in the toolbar.

In previous versions you could have it hidden, _(ie. putting in in “Additional Tools and Features”)_, and it still worked.

If it's possible - could you please bring that behaviour back?

_// Perhaps related: #97_
