### ISSUE TITLE
Firefox show two different emoji types as one

### ISSUE THREAD

**Issue by Daisenki** [johannhof/emoji-helper#96]
Can some one please help me, I'm getting crazy with that?! Firefox change every emoji type and I don't know why he does that, I can't find any real helpful information about that.

😀  <-  should it look like in my screenshot? I don't want that, I want the emoji from the addon.

<img width="436" alt="snip_20170718193935" src="https://user-images.githubusercontent.com/22057956/28331318-db637fc4-6bf0-11e7-997c-2cbd76cf9f61.png">
 
<img width="181" alt="snip_20170718193418" src="https://user-images.githubusercontent.com/22057956/28331181-634d5dd4-6bf0-11e7-9ec7-e7fd1b6ddef7.png">

<img width="140" alt="snip_20170718194300" src="https://user-images.githubusercontent.com/22057956/28331442-5d895582-6bf1-11e7-9837-e20e679f624a.png">

**Comment by johannhof** [comment]
I think that's the new Windows Emojis. Unfortunately that set looks quite different from the "regular" ones or even the EmojiOne that Firefox is bundling if your OS doesn't support Emoji.

So I don't think there's much this extension or Firefox can do about it, sorry.

**Comment by Daisenki** [comment]
No, that's a old set of Emojis, the new Windows10 set looks different. I see this classic Emojis here: http://classic.getemoji.com/

Isn't there a way to force your Emojis?
