### ISSUE TITLE
The keyboard shortcut is broken

### ISSUE THREAD

**Issue by Keiishu** [johannhof/emoji-helper#97]
Hello,
Since the latest update of Firefox, Control-Shift-E is assigned to the network console. We can't open up the emoji picker anymore because of that.

(Firefox 55.0.3 32 bits on Windows 10 Pro 64 bits)

**Comment by MarkRH** [comment]
Actually, I keep opening the Emoji Helper window and not the Network Console which is what I really want. In any case, the shortcut needs to change or be user defined. :)

**Comment by Nikolajls** [comment]
Mine 55.0.3 FF also keeps opening the network console which is pretty annoying.
Not sure why the earlier version with total custom shortcut was removed ?

**Comment by MarkRH** [comment]
FYI, CTRL-Shift-E does open it up in Firefox 57beta.  The Network Console is still Ctrl-Shift-E but looks like the extension sees the short-cut first.  In 56 is opens the Network Console.

**Comment by Deuchnord** [comment]
Hello
It would be great to be add a way to change the keyboard shortcut. Here on GNU/Linux, Ctrl-Shift-E is used by come desktop environment to insert emojis from a code. 💋
![GIF showing the result of Ctrl-Shift-E followed by "kiss" and Enter](https://user-images.githubusercontent.com/7600265/32416143-ca0c062e-c244-11e7-82d9-8e8b7fb6f6cf.gif)

**Comment by techgique** [comment]
I use Dev Edition and it seems unpredictable whether the Emoji extension or the Network Monitor will bind to Ctrl+Shift+E each time I start the browser. Making this extension's shortcut user-definable would be great!

**Comment by BobbyWibowo** [comment]
+1. I'm using Ctrl+Shift+E for global selection screenshot app and it's already a habit, lol
